name: Sportlynk
favicon: null
layout_spectrum: 0.48112
typography_spectrum: 0.12814082251861691
title: Draft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#243151'
    - '#516ca1'
    - '#070a11'
    - '#405439'
    - '#7993c6'
  brandStrength: 0.5625
  lightness: 0.6950171494390815
  saturation: 0.9833636027760804
  rhythmicContrast: 0.9969601552002132
purpose: []
