name: Sportlynk
favicon: null
layout_spectrum: 0.45499458629637957
typography_spectrum: 0.12814082251861691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41075592720881104
  lightness: 0.6950171494390815
  saturation: 0.9833636027760804
  rhythmicContrast: 0.9969601552002132
purpose: []
